
'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';
import { ThemeProvider } from 'next-themes';

type Language = 'id' | 'en' | 'es' | 'pt' | 'de' | 'fr' | 'it';

interface TranslationDictionary {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: TranslationDictionary = {
  id: {
    title: "VersoKit",
    subtitle: "Toolkit Lengkap untuk Olahraga & Bisnis",
    dashboard: "Dasbor",
    futsal: "Papan Skor Futsal",
    budget_planner: "Rencana Anggaran",
    lineup: "Penyusun Formasi",
    scoreboard: "Skor Universal",
    inventory: "Inventaris",
    kanban: "Papan Tugas",
    tournament: "Manajer Turnamen",
    csv_helper: "Pembersih CSV",
    calculator: "Kalkulator Material",
    invoice: "Pembuat Invoice",
    shift: "Jadwal Shift",
    image_compressor: "Kompres Gambar",
    split_bill: "Patungan / Split Bill",
    pdf_merge: "Gabung PDF",
    image_to_pdf: "Gambar ke PDF",
    export: "Ekspor CSV",
    import: "Impor CSV",
    reset: "Reset",
    add: "Tambah",
    delete: "Hapus",
    status: "Status",
    todo: "Rencana",
    progress: "Proses",
    done: "Selesai",
    home: "Kandang",
    away: "Tandang",
    score: "Skor",
    fouls: "Pelanggaran",
    time: "Waktu",
    start: "Mulai",
    pause: "Jeda",
    target_score: "Target Skor",
    team_name: "Nama Tim",
    add_item: "Tambah Barang",
    add_player: "Tambah Peserta",
    generate: "Buat Jadwal",
    dimensions: "Dimensi",
    area: "Luas",
    cost: "Estimasi Biaya",
    preview: "Pratinjau",
    remove_dupes: "Hapus Duplikat",
    download: "Unduh",
    print: "Cetak / Simpan PDF",
    client_name: "Nama Klien",
    business_name: "Nama Bisnis",
    date: "Tanggal",
    item_name: "Nama Barang",
    qty: "Jml",
    price: "Harga",
    total: "Total",
    grand_total: "Total Keseluruhan",
    employee_name: "Nama Karyawan",
    mon: "Sen", tue: "Sel", wed: "Rab", thu: "Kam", fri: "Jum", sat: "Sab", sun: "Min",
    cat_sports: "Olahraga", cat_business: "Bisnis", cat_utilities: "Alat Bantu"
  },
  en: {
    title: "VersoKit",
    subtitle: "Complete Toolkit for Sports & Business",
    dashboard: "Dashboard",
    futsal: "Futsal Scoreboard",
    budget_planner: "Budget Planner",
    lineup: "Lineup Builder",
    scoreboard: "Universal Scoreboard",
    inventory: "Inventory",
    kanban: "Kanban Board",
    tournament: "Tournament Manager",
    csv_helper: "CSV Cleaner",
    calculator: "Material Calculator",
    invoice: "Invoice Maker",
    shift: "Shift Roster",
    image_compressor: "Image Compressor",
    split_bill: "Split Bill",
    pdf_merge: "Merge PDF",
    image_to_pdf: "Image to PDF",
    export: "Export CSV",
    import: "Import CSV",
    reset: "Reset",
    add: "Add",
    delete: "Delete",
    status: "Status",
    todo: "To Do",
    progress: "In Progress",
    done: "Done",
    home: "Home",
    away: "Away",
    score: "Score",
    fouls: "Fouls",
    time: "Time",
    start: "Start",
    pause: "Pause",
    target_score: "Target Score",
    team_name: "Team Name",
    add_item: "Add Item",
    add_player: "Add Participant",
    generate: "Generate Schedule",
    dimensions: "Dimensions",
    area: "Area",
    cost: "Estimated Cost",
    preview: "Preview",
    remove_dupes: "Remove Duplicates",
    download: "Download",
    print: "Print / Save PDF",
    client_name: "Client Name",
    business_name: "Business Name",
    date: "Date",
    item_name: "Item Name",
    qty: "Qty",
    price: "Price",
    total: "Total",
    grand_total: "Grand Total",
    employee_name: "Employee Name",
    mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat", sun: "Sun",
    cat_sports: "Sports", cat_business: "Business", cat_utilities: "Utilities"
  },
  es: {
    title: "VersoKit",
    subtitle: "Herramientas para Deportes y Negocios",
    dashboard: "Tablero",
    futsal: "Pizarra Futsal",
    budget_planner: "Presupuesto",
    lineup: "Alineaciones",
    scoreboard: "Marcador Universal",
    inventory: "Inventario",
    kanban: "Kanban",
    tournament: "Torneos",
    csv_helper: "Limpiador CSV",
    calculator: "Calculadora",
    invoice: "Facturas",
    shift: "Turnos",
    image_compressor: "Comprimir Imagen",
    split_bill: "Dividir Cuenta",
    pdf_merge: "Unir PDF",
    image_to_pdf: "Imagen a PDF",
    export: "Exportar",
    import: "Importar",
    reset: "Reiniciar",
    add: "Añadir",
    delete: "Eliminar",
    status: "Estado",
    todo: "Pendiente",
    progress: "En Proceso",
    done: "Hecho",
    home: "Local",
    away: "Visitante",
    score: "Puntos",
    fouls: "Faltas",
    time: "Tiempo",
    start: "Inicio",
    pause: "Pausa",
    target_score: "Objetivo",
    team_name: "Equipo",
    add_item: "Añadir Artículo",
    add_player: "Añadir Jugador",
    generate: "Generar",
    dimensions: "Dimensiones",
    area: "Área",
    cost: "Costo",
    preview: "Vista Previa",
    remove_dupes: "Quitar Duplicados",
    download: "Descargar",
    print: "Imprimir PDF",
    client_name: "Cliente",
    business_name: "Empresa",
    date: "Fecha",
    item_name: "Artículo",
    qty: "Cant",
    price: "Precio",
    total: "Total",
    grand_total: "Total General",
    employee_name: "Empleado",
    mon: "Lun", tue: "Mar", wed: "Mié", thu: "Jue", fri: "Vie", sat: "Sáb", sun: "Dom",
    cat_sports: "Deportes", cat_business: "Negocios", cat_utilities: "Utilidades"
  },
  pt: {
    title: "VersoKit",
    subtitle: "Ferramentas para Esportes e Negócios",
    dashboard: "Painel",
    futsal: "Placar Futsal",
    budget_planner: "Orçamento",
    lineup: "Escalação",
    scoreboard: "Placar Universal",
    inventory: "Inventário",
    kanban: "Kanban",
    tournament: "Torneios",
    csv_helper: "Limpar CSV",
    calculator: "Calculadora",
    invoice: "Faturas",
    shift: "Escalas",
    image_compressor: "Comprimir Imagem",
    split_bill: "Dividir Conta",
    pdf_merge: "Juntar PDF",
    image_to_pdf: "Imagem para PDF",
    export: "Exportar",
    import: "Importar",
    reset: "Resetar",
    add: "Adicionar",
    delete: "Excluir",
    status: "Status",
    todo: "Para Fazer",
    progress: "Em Andamento",
    done: "Concluído",
    home: "Mandante",
    away: "Visitante",
    score: "Placar",
    fouls: "Faltas",
    time: "Tempo",
    start: "Iniciar",
    pause: "Pausa",
    target_score: "Meta",
    team_name: "Time",
    add_item: "Adicionar Item",
    add_player: "Adicionar Jogador",
    generate: "Gerar",
    dimensions: "Dimensões",
    area: "Área",
    cost: "Custo",
    preview: "Prévia",
    remove_dupes: "Remover Duplicados",
    download: "Baixar",
    print: "Imprimir PDF",
    client_name: "Cliente",
    business_name: "Empresa",
    date: "Data",
    item_name: "Item",
    qty: "Qtd",
    price: "Preço",
    total: "Total",
    grand_total: "Total Geral",
    employee_name: "Funcionário",
    mon: "Seg", tue: "Ter", wed: "Qua", thu: "Qui", fri: "Sex", sat: "Sáb", sun: "Dom",
    cat_sports: "Esportes", cat_business: "Negócios", cat_utilities: "Utilidades"
  },
  de: {
    title: "VersoKit",
    subtitle: "Toolkit für Sport & Business",
    dashboard: "Dashboard",
    futsal: "Futsal-Scoreboard",
    budget_planner: "Budget-Planer",
    lineup: "Aufstellung",
    scoreboard: "Universal-Scoreboard",
    inventory: "Inventar",
    kanban: "Kanban",
    tournament: "Turniere",
    csv_helper: "CSV-Reiniger",
    calculator: "Rechner",
    invoice: "Rechnungen",
    shift: "Schichtplan",
    image_compressor: "Bild-Kompressor",
    split_bill: "Rechnung teilen",
    pdf_merge: "PDF verbinden",
    image_to_pdf: "Bild zu PDF",
    export: "Exportieren",
    import: "Importieren",
    reset: "Reset",
    add: "Hinzufügen",
    delete: "Löschen",
    status: "Status",
    todo: "Aufgaben",
    progress: "In Arbeit",
    done: "Erledigt",
    home: "Heim",
    away: "Gast",
    score: "Punkte",
    fouls: "Fouls",
    time: "Zeit",
    start: "Start",
    pause: "Pause",
    target_score: "Ziel",
    team_name: "Team",
    add_item: "Teil hinzufügen",
    add_player: "Teilnehmer hinzufügen",
    generate: "Erstellen",
    dimensions: "Maße",
    area: "Fläche",
    cost: "Kosten",
    preview: "Vorschau",
    remove_dupes: "Duplikate löschen",
    download: "Download",
    print: "PDF Drucken",
    client_name: "Kunde",
    business_name: "Firma",
    date: "Datum",
    item_name: "Artikel",
    qty: "Stk",
    price: "Preis",
    total: "Summe",
    grand_total: "Gesamtsumme",
    employee_name: "Mitarbeiter",
    mon: "Mo", tue: "Di", wed: "Mi", thu: "Do", fri: "Fr", sat: "Sa", sun: "So",
    cat_sports: "Sport", cat_business: "Business", cat_utilities: "Tools"
  },
  fr: {
    title: "VersoKit",
    subtitle: "Outils Sport & Business",
    dashboard: "Tableau",
    futsal: "Score Futsal",
    budget_planner: "Budget",
    lineup: "Composition",
    scoreboard: "Score Universel",
    inventory: "Inventaire",
    kanban: "Kanban",
    tournament: "Tournois",
    csv_helper: "Nettoyeur CSV",
    calculator: "Calculatrice",
    invoice: "Factures",
    shift: "Planning",
    image_compressor: "Compresser Image",
    split_bill: "Partager l'addition",
    pdf_merge: "Fusionner PDF",
    image_to_pdf: "Image en PDF",
    export: "Exporter",
    import: "Importer",
    reset: "Réinitialiser",
    add: "Ajouter",
    delete: "Supprimer",
    status: "Statut",
    todo: "À faire",
    progress: "En cours",
    done: "Terminé",
    home: "Domicile",
    away: "Extérieur",
    score: "Score",
    fouls: "Fautes",
    time: "Temps",
    start: "Démarrer",
    pause: "Pause",
    target_score: "Objectif",
    team_name: "Équipe",
    add_item: "Ajouter article",
    add_player: "Ajouter joueur",
    generate: "Générer",
    dimensions: "Dimensions",
    area: "Surface",
    cost: "Coût",
    preview: "Aperçu",
    remove_dupes: "Supprimer doublons",
    download: "Télécharger",
    print: "Imprimer PDF",
    client_name: "Client",
    business_name: "Entreprise",
    date: "Date",
    item_name: "Article",
    qty: "Qté",
    price: "Prix",
    total: "Total",
    grand_total: "Total général",
    employee_name: "Employé",
    mon: "Lun", tue: "Mar", wed: "Mer", thu: "Jeu", fri: "Ven", sat: "Sam", sun: "Dim",
    cat_sports: "Sports", cat_business: "Affaires", cat_utilities: "Utilitaires"
  },
  it: {
    title: "VersoKit",
    subtitle: "Strumenti Sport e Business",
    dashboard: "Dashboard",
    futsal: "Tabellone Futsal",
    budget_planner: "Budget",
    lineup: "Formazione",
    scoreboard: "Score Universale",
    inventory: "Inventario",
    kanban: "Kanban",
    tournament: "Tornei",
    csv_helper: "Pulizia CSV",
    calculator: "Calcolatrice",
    invoice: "Fatture",
    shift: "Turni",
    image_compressor: "Comprimi Immagine",
    split_bill: "Dividi Conto",
    pdf_merge: "Unisci PDF",
    image_to_pdf: "Immagine in PDF",
    export: "Esporta",
    import: "Importa",
    reset: "Reset",
    add: "Aggiungi",
    delete: "Elimina",
    status: "Stato",
    todo: "Da fare",
    progress: "In corso",
    done: "Fatto",
    home: "Casa",
    away: "Trasferta",
    score: "Punti",
    fouls: "Falli",
    time: "Tempo",
    start: "Inizia",
    pause: "Pausa",
    target_score: "Obiettivo",
    team_name: "Squadra",
    add_item: "Aggiungi articolo",
    add_player: "Aggiungi giocatore",
    generate: "Genera",
    dimensions: "Dimensioni",
    area: "Area",
    cost: "Costo",
    preview: "Anteprima",
    remove_dupes: "Rimuovi duplicati",
    download: "Scarica",
    print: "Stampa PDF",
    client_name: "Cliente",
    business_name: "Azienda",
    date: "Data",
    item_name: "Articolo",
    qty: "Qta",
    price: "Prezzo",
    total: "Totale",
    grand_total: "Totale Generale",
    employee_name: "Dipendente",
    mon: "Lun", tue: "Mar", wed: "Mer", thu: "Gio", fri: "Ven", sat: "Sab", sun: "Dom",
    cat_sports: "Sport", cat_business: "Business", cat_utilities: "Utilità"
  }
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLang() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLang must be used within LanguageProvider');
  return context;
}

export function Providers({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('id');

  useEffect(() => {
    const savedLang = localStorage.getItem('versokit-lang') as Language;
    if (savedLang) setLang(savedLang);
  }, []);

  const handleSetLang = (newLang: Language) => {
    setLang(newLang);
    localStorage.setItem('versokit-lang', newLang);
  };

  const t = (key: string) => translations[lang]?.[key] || key;

  return (
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
        {children}
      </LanguageContext.Provider>
    </ThemeProvider>
  );
}
